language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python test/__init__.py